{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.0.2/lib-0.0.2.module",
    "group": "ru.uni",
    "module": "lib",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "brpwmwlk45d3jcgyqej7geklea"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lib-jvm-0.0.2.jar",
          "url": "lib-0.0.2.jar",
          "size": 69578,
          "sha512": "b608db17d381976e0d6c101c2a81ea9e8c0860f255be9a9b4847649c422025fce06533c2a306e4ad16383fb54fd855517bf382214baa91c6d022f4f1e465147a",
          "sha256": "a259fe57852f2cc02ba068575bbf91aadcdab6c8023d2c9def4e72858bd8b704",
          "sha1": "e3fb3bcb140252a81fcfc375e90322a72f3bac99",
          "md5": "5ae9a70a861cc379d8b6a79652b41f26"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.0.2.jar",
          "url": "lib-0.0.2.jar",
          "size": 69578,
          "sha512": "b608db17d381976e0d6c101c2a81ea9e8c0860f255be9a9b4847649c422025fce06533c2a306e4ad16383fb54fd855517bf382214baa91c6d022f4f1e465147a",
          "sha256": "a259fe57852f2cc02ba068575bbf91aadcdab6c8023d2c9def4e72858bd8b704",
          "sha1": "e3fb3bcb140252a81fcfc375e90322a72f3bac99",
          "md5": "5ae9a70a861cc379d8b6a79652b41f26"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../lib-metadata/0.0.2/lib-metadata-0.0.2.module",
        "group": "ru.uni",
        "module": "lib-metadata",
        "version": "0.0.2"
      }
    }
  ]
}
