{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.uni",
    "module": "lib-gradle",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "uowfwh6r7nhedef3kbmpfzjyai"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lib-gradle-0.0.1.jar",
          "url": "lib-gradle-0.0.1.jar",
          "size": 1145,
          "sha512": "3fbf28885c1ec7580a330c79a89bdb655900c22a88d35e52a3b5c7df3bc0c6ac7591281dbe0064673549bd6d2646dd2bee70c52ab927b1f818afabb1acda4ba1",
          "sha256": "0b9e79bc9946a71fa16039bc800518105b372ec9402e98b71df6fc9fb1406655",
          "sha1": "c84496b33f757ea40adf16955ed912173db2a368",
          "md5": "9c4275889f658a72b36e14be7d6886de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "ru.uni",
          "module": "lib",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-gradle-0.0.1.jar",
          "url": "lib-gradle-0.0.1.jar",
          "size": 1145,
          "sha512": "3fbf28885c1ec7580a330c79a89bdb655900c22a88d35e52a3b5c7df3bc0c6ac7591281dbe0064673549bd6d2646dd2bee70c52ab927b1f818afabb1acda4ba1",
          "sha256": "0b9e79bc9946a71fa16039bc800518105b372ec9402e98b71df6fc9fb1406655",
          "sha1": "c84496b33f757ea40adf16955ed912173db2a368",
          "md5": "9c4275889f658a72b36e14be7d6886de"
        }
      ]
    }
  ]
}
