name: 'pr'
on:
  pull_request:
env:
  SSH_AUTH_SOCK: "/tmp/ssh_agent_${{github.run_id}}.sock"
#  UNI_RELEASE: "true"

jobs:
  unit-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with: {java-version: 11}
#      - name: file from secret
#        uses: avdim/create-file-action@1.0.0
#        env:
#          FILE_NAME: "temp_id_rsa"
#          FILE_DATA: "${{ secrets.SSH_PRIVATE }}"
      - name: Setup SSH
        env:
          SSH_PRIVATE: ${{secrets.SSH_PRIVATE}}
        run: |
          ssh-agent -k || echo "skip"
          mkdir -p ~/.ssh
          #ssh-keyscan github.com >> ~/.ssh/known_hosts
          for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "$SSH_PRIVATE"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - run: ./gradlew test
      - run: ./gradlew uni-idea-plugin:buildPlugin -PuniBuildType=release
      - name: upload plugin to github release page
        uses: avdim/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "uni-idea-plugin/build/distributions/*"
          tags: false
          draft: true
          prerelease: false
          overwrite: true


